# Use an official Rust runtime as a parent image
FROM rust:1.73.0 as builder

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY .. .

# Install protobuf-compiler
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends protobuf-compiler \
 && rm -rf /var/lib/apt/lists/*

# Build the server program using Cargo
RUN cargo build --release

# Start a new stage and copy the server binary from the builder stage
FROM rust:1.73.0
COPY --from=builder /app/target/release/server /usr/local/bin/server
COPY --from=builder /app/target/release/client /usr/local/bin/client

# Copy the test script into the container
COPY --from=builder /app/docker/test_script.sh /app/test_script.sh
RUN chmod +x /app/test_script.sh

# Set the entrypoint to the test script
ENTRYPOINT ["/app/test_script.sh"]
